"""initial

Revision ID: e18f06b2a7ed
Revises: 
Create Date: 2026-05-26 14:22:46.663073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18f06b2a7ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lancamentos_contabeis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('historico', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plano_contas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('natureza', sa.String(length=10), nullable=False),
    sa.Column('conta_pai_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conta_pai_id'], ['plano_contas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('estoque', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('itens_lancamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lancamento_id', sa.Integer(), nullable=False),
    sa.Column('conta_debito_id', sa.Integer(), nullable=False),
    sa.Column('conta_credito_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['conta_credito_id'], ['plano_contas.id'], ),
    sa.ForeignKeyConstraint(['conta_debito_id'], ['plano_contas.id'], ),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos_contabeis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacoes_estoque')
    op.drop_table('itens_lancamento')
    op.drop_table('usuarios')
    op.drop_table('produtos')
    op.drop_table('plano_contas')
    op.drop_table('lancamentos_contabeis')
    # ### end Alembic commands ###
